In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

b = np.array([[1.6,2.12,3.14],[6.9,5.0,3.0]])
print(b)

[1 2 3]
[[1.6  2.12 3.14]
 [6.9  5.   3.  ]]


In [ ]:
#Get dimension
b.ndim

2

In [ ]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# get type
a.dtype

dtype('int16')

In [ ]:
# Get size
a.itemsize

4

In [ ]:
#Get total size
a.size * a.itemsize


12

In [ ]:
#Get total size
a.nbytes

12

In [ ]:
b.itemsize


8

In [ ]:
a =  np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a[1,3]

11

In [ ]:
a[:,0]

array([1, 8])

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[1,1,1]

8

In [ ]:
b[:,:,1] = [[5,5] ,[6,6]]
print(b)

[[[1 5]
  [3 5]]

 [[5 6]
  [7 6]]]


In [ ]:
# Initializing Different Types of Arrays

In [ ]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [ ]:
#All 1s matrix
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
#Any other number

In [ ]:
np.full((2,2) , 5)

array([[5, 5],
       [5, 5]])

In [ ]:
# Any other numner (full_like)
print(a)
np.full_like(a, 2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)
#if you wanna pass a shape then use
np.random.random_sample(a.shape)

array([[0.47222753, 0.79936856, 0.08885465, 0.62299326, 0.79853653,
        0.48429402, 0.97744262],
       [0.26847438, 0.36351874, 0.89272987, 0.8542448 , 0.90878691,
        0.65793277, 0.88787225]])

In [ ]:
b.shape

(2, 2, 2)

In [ ]:
array = np.arange(8)
print(array , "\n")
array = np.arange(8).reshape(2,4)
print(array , "\n")
array = np.arange(8).reshape(2,2,2)
print(array , "\n")

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



In [ ]:
a = np.identity(5)
print (a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a [2,2] = 9

In [ ]:
print (a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1]= 9
print(z, '\n')

output [1:4,1:4] = z
print(output)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be Careful when copying arrays!!**






In [ ]:
a = np.array([1,2,3])
b = a #b points to same as a. b isnt a copy here
b[0] = 100
print (a)
b = a.copy()
b[0] = 200
print (a)

[100   2   3]
[100   2   3]
